### ISSUE TITLE
Unable to load tensorflow lib on (M1) Mac

### ISSUE THREAD

**Issue by Webreaper** [DaniJG/blazor-ml#1]
Hi, I'm super-interested in this project, because I'm writing a Blazor server [image-management app](https://github.com/webreaper/damselfly) and would like to add some image-recognition (and perhaps face-recognition) to it too. 

However, when I try and run your sample on my M1 MacBook, I get an error that it can't load tensorflow - the library:

```
{System.DllNotFoundException: Unable to load shared library 'tensorflow' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libtensorflow, 1): image not found
   at Tensorflow.c_api.TF_NewGraph()
   at Tensorflow.Graph..ctor()
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)}
```

Did you ever get this working on a Mac? It's unclear whether the issue is because I'm on a Mac, or because it's an M1 Mac (although I hoped this would work under Rosetta 2). I even tried compiling a linux-x64 version and copying it onto my linux NAS, but it also fails to start....

**Comment by Webreaper** [comment]
Okay, looks like adding a reference to Microsoft.ML.TensorFlow.Redist made this work.

**Comment by DaniJG** [comment]
great to hear that worked @Webreaper . I created this sample project using .NET Core 3.1 for a [DNC article](https://www.dotnetcurry.com/ShowArticle.aspx?ID=1537) and haven't really upgraded to newer .NET versions.

I am assuming the original `SciSharp.TensorFlow.Redist` dependency is now superseded/replaced by `Microsoft.ML.TensorFlow.Redist` ?

**Comment by Webreaper** [comment]
That seems to be the case, although I can't find it documented anywhere (it was hard enough to find at all). I also found that if you add a reference to runtime.osx.10.10-x64.CoreCompat.System.Drawing and System.Drawing.Common, it solves the GDI+ dependency too (this is all with .Net 5 or 6).

Slightly ranty thread here: https://twitter.com/DamselflyPhotos/status/1405976331561713669 :)

**Comment by DaniJG** [comment]
Sounds quite frustrating! At least you managed to find the solution, which is quite helpful.

I should update the project to at least .NET 5 and hopefully save someone else from going through the same experience (this could very well be me in the near future haha)

**Comment by Webreaper** [comment]
Yeah, it's one of those things that was frustrating until you find it, but then obvious....

I haven't tried this on Linux yet, but will try the apt get stuff for the GDI packages when I put it in Docker, and report back. I looked at replacing it with ImageSharp (which I already use) but I think ML.Net uses System.Drawing internally regardless.

Youll need to upgrade the syntax for the image uploaded and selector in the Blazor code too, when you move to 5.0.
